### ISSUE TITLE
error occur when run "python aster/demo.py"

### ISSUE THREAD

**Issue by LiangHao92** [bgshih/aster#21]
I get the error:
Traceback (most recent call last):
  File "aster/demo.py", line 9, in <module>
    from aster.builders import model_builder
  File "/home/seven/Downloads/aster/builders/model_builder.py", line 5, in <module>
    from aster.builders import predictor_builder
  File "/home/seven/Downloads/aster/builders/predictor_builder.py", line 9, in <module>
    from aster.predictors import attention_predictor
  File "/home/seven/Downloads/aster/predictors/attention_predictor.py", line 14, in <module>
    from aster.c_ops import ops
  File "/home/seven/Downloads/aster/c_ops/ops.py", line 26, in <module>
    _oplib = _load_oplib(FLAGS.oplib_name)
  File "/home/seven/Downloads/aster/c_ops/ops.py", line 23, in _load_oplib
    oplib = tf.load_op_library(lib_copy_path)
  File "/home/seven/anaconda2/envs/aster/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/seven/anaconda2/envs/aster/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /tmp/libaster_ac83631a.so: undefined symbol: _ZNK10tensorflow14TensorShapeRep11DebugStringEv

**Comment by ChChwang** [comment]
--exp_dir ....

**Comment by LiangHao92** [comment]
@ChChwang 我调用demo函数，并不需要exp_dir吧

**Comment by Antonio-hi** [comment]
@LiangHao92 我也遇到了同样的问题，请问你解决了吗？

**Comment by Horace89** [comment]
I think I have a similar problem

> seb@asp-V3-371:~/scene_text$ python aster/demo.py 
> 
> Traceback (most recent call last):
>   File "aster/demo.py", line 9, in <module>
>     from aster.builders import model_builder
>   File "/home/seb/scene_text/aster/builders/model_builder.py", line 5, in <module>
>     from aster.builders import predictor_builder
>   File "/home/seb/scene_text/aster/builders/predictor_builder.py", line 9, in <module>
>     from aster.predictors import attention_predictor
>   File "/home/seb/scene_text/aster/predictors/attention_predictor.py", line 14, in <module>
>     from aster.c_ops import ops
>   File "/home/seb/scene_text/aster/c_ops/ops.py", line 26, in <module>
>     _oplib = _load_oplib(FLAGS.oplib_name)
>   File "/home/seb/scene_text/aster/c_ops/ops.py", line 23, in _load_oplib
>     oplib = tf.load_op_library(lib_copy_path)
>   File "/home/seb/.virtualenvs/aster/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
>   File "/home/seb/.virtualenvs/aster/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: /tmp/libaster_cb061527.so: undefined symbol: _ZN10tensorflow15OpKernelContext10CtxFailureEPKciRKNS_6StatusE
> 

I'm on Ubuntu 16.04, Python 3.5.2, and Tensorflow 1.4.0

**Comment by Nioolek** [comment]
@LiangHao92 Hello.I have the same problem. Have you solved it?If so, how?

**Comment by findneo** [comment]
maybe caused by [tensorflow bug](https://github.com/tensorflow/tensorflow/issues/13607) , version 1.4.0 works well.

**Comment by lifeGWT** [comment]
> Hello.I have the same problem. Have you solved it?If so, how?

**Comment by lifeGWT** [comment]
> @LiangHao92 Hello.I have the same problem. Have you solved it?If so, how?

**Comment by lifeGWT** [comment]
@Nioolek Hello.I have the same problem. Have you solved it?If so, how?

**Comment by IngleJaya95** [comment]
> @Nioolek Hello.I have the same problem. Have you solved it?If so, how?

Use tensorflow version 1.4.0

**Comment by zahidzqj** [comment]
File "/home/dell/anaconda/lib/python3.5/inspect.py", line 1050, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
how to solve?

**Comment by Nioolek** [comment]
> > @Nioolek你好。我有同样的问题。你解决了吗？如果有，怎么样？
> 
> 使用tensorflow版本1.4.0

I use tensorflow==1.4.0,and code work

**Comment by Nioolek** [comment]
> > @Nioolek你好。我有同样的问题。你解决了吗？如果有，怎么样？
> 
> 使用tensorflow版本1.4.0

Thank you

**Comment by Dkili** [comment]
Hello,

I have the same problem with tensorflow==1.4.0 (Ubuntu 16.04). I also have tried older and recent version of tensorflow (1.3 ~ 1.5) but it didn't change anything. 
Does anyone have a clue on how to solve this problem ?
Thank you.

**Comment by donglin8506** [comment]
@Dkili I find that tensorflow==1.4.1 (ubuntu16.04) is ok. Use `conda install tensorflow-gpu==1.4.1`. By commond `conda search tensorflow-gpu `,  don't find 1.4.0 version , only have three version (1.3.0、1.4.1、1.5.0 ) nearby. In addition, if use version 1.3.0, next step `./build.sh` will occur error (...'lobster.so' faild ... ). I hope this is useful to you.

**Comment by zaghdoud2019** [comment]
> > > @Nioolek你好。我有同样的问题。你解决了吗？如果有，怎么样？
> > 
> > 
> > 使用tensorflow版本1.4.0
> 
> Thank you

please can you sent to me the complete code .thanks to reply
