### ISSUE TITLE
I have some problem about demo.py?

### ISSUE THREAD

**Issue by lzmisscc** [bgshih/aster#59]
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:root:Number of classes is 94
INFO:root:UNK label is 2
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:root:Number of classes is 94
INFO:root:UNK label is 2
WARNING:tensorflow:From /home/lz/PycharmProjects/aster/core/spatial_transformer.py:111: calling norm (from tensorflow.python.ops.linalg_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
Traceback (most recent call last):
  File "demo.py", line 92, in <module>
    tf.app.run()
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "demo.py", line 55, in main
    predictions_dict = model.predict(tf.expand_dims(resized_image_tensor, 0))
  File "/home/lz/PycharmProjects/aster/meta_architectures/multi_predictors_recognition_model.py", line 51, in predict
    predictor_outputs = predictor.predict(feature_maps, scope='{}/Predictor'.format(name))
  File "/home/lz/PycharmProjects/aster/predictors/attention_predictor.py", line 74, in predict
    maximum_iterations=self._max_num_steps
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 322, in dynamic_decode
    swap_memory=swap_memory)
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3260, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 265, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py", line 657, in step
    cell_outputs, next_cell_state = self._cell(inputs, cell_state)
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 233, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 374, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/lz/.conda/envs/tf/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/lz/PycharmProjects/aster/core/sync_attention_wrapper.py", line 54, in call
    self._attention_layers[i] if self._attention_layers else None)
ValueError: too many values to unpack (expected 2)

**Comment by hwwu** [comment]
之前有人回答了这个问题，主要是因为tf版本问题引起的，引用一下之前的回答：
ValueError: too many values to unpack (expected 2)
这个问题，在core/sync_attention_wrapper.py里面，attention, alignments, attention_state = _compute_attention，这个返回了三个值，所以添加了这个attention_state，并且在下面next_state = seq2seq.AttentionWrapperState这个里面，缺了一项，缺了attention_state这个参数，我直接将上面返回的attention_state给了这个输入，现在demo可以跑了
@bgshih 不知道这样是不是正确的

**Comment by lzmisscc** [comment]
> 之前有人回答了这个问题，主要是因为tf版本问题引起的，引用一下之前的回答：
> ValueError: too many values to unpack (expected 2)
> 这个问题，在core/sync_attention_wrapper.py里面，attention, alignments, attention_state = _compute_attention，这个返回了三个值，所以添加了这个attention_state，并且在下面next_state = seq2seq.AttentionWrapperState这个里面，缺了一项，缺了attention_state这个参数，直接将上面返回的attention_state给了这个输入

Thanks
