### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by liu100286** [bgshih/aster#79]
File "aster/demo.py", line 92, in <module>
    tf.app.run()
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "aster/demo.py", line 55, in main
    predictions_dict = model.predict(tf.expand_dims(resized_image_tensor, 0))
  File "/home/liu/aster/meta_architectures/multi_predictors_recognition_model.py", line 51, in predict
    predictor_outputs = predictor.predict(feature_maps, scope='{}/Predictor'.format(name))
  File "/home/liu/aster/predictors/attention_predictor.py", line 74, in predict
    maximum_iterations=self._max_num_steps
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 322, in dynamic_decode
    swap_memory=swap_memory)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
    return_same_structure)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3022, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3525, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 265, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py", line 658, in step
    cell_outputs, next_cell_state = self._cell(inputs, cell_state)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 234, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/liu/aster/core/sync_attention_wrapper.py", line 54, in call
    self._attention_layers[i] if self._attention_layers else None)
ValueError: too many values to unpack (expected 2)

I'll follow your instructions.

But I don't know the reason for this mistake.

**Comment by liu100286** [comment]
(py-tensorflow-cpu) root@AI:/home/liu# python3 aster/demo.py 
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From /home/liu/aster/builders/rnn_cell_builder.py:23: LSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:root:Number of classes is 94
INFO:root:UNK label is 2
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:root:Number of classes is 94
INFO:root:UNK label is 2
WARNING:tensorflow:From aster/demo.py:52: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/liu/aster/core/spatial_transformer.py:111: calling norm (from tensorflow.python.ops.linalg_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
WARNING:tensorflow:From /home/liu/aster/core/bidirectional_rnn.py:72: static_bidirectional_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN(cell, unroll=True))`, which is equivalent to this API
WARNING:tensorflow:From /root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:1565: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell, unroll=True)`, which is equivalent to this API
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
Traceback (most recent call last):
  File "aster/demo.py", line 92, in <module>
    tf.app.run()
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "aster/demo.py", line 55, in main
    predictions_dict = model.predict(tf.expand_dims(resized_image_tensor, 0))
  File "/home/liu/aster/meta_architectures/multi_predictors_recognition_model.py", line 51, in predict
    predictor_outputs = predictor.predict(feature_maps, scope='{}/Predictor'.format(name))
  File "/home/liu/aster/predictors/attention_predictor.py", line 74, in predict
    maximum_iterations=self._max_num_steps
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 322, in dynamic_decode
    swap_memory=swap_memory)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
    return_same_structure)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3022, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3525, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 265, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py", line 658, in step
    cell_outputs, next_cell_state = self._cell(inputs, cell_state)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 234, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/root/Envs/py-tensorflow-cpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/liu/aster/core/sync_attention_wrapper.py", line 54, in call
    self._attention_layers[i] if self._attention_layers else None)
ValueError: too many values to unpack (expected 2)




What I did was: "aster / demo. py"
